# ============================================================
# Author: TGibson
# File: services/scoring/helm/templates/deployment.yaml
# Repo: AWS EKS CI/CD (Commercial + GovCloud) via CloudFormation
# Version: 1.1
# Date: 2025-08-27
# ============================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scoring
spec:
  replicas: {{ .Values.replicaCount }}
  selector: { matchLabels: { app: scoring } }
  template:
    metadata:
      labels: { app: scoring }
    spec:
      serviceAccountName: default
      containers:
        - name: scoring
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: [{ containerPort: 8080, name: http }]
          env:
            - name: EVENT_BUS_NAME
              value: "{{ .Values.env.EVENT_BUS_NAME }}"
            - name: TENANT_CLAIM
              value: "{{ .Values.env.TENANT_CLAIM }}"
          readinessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 5
          env:
            - name: JOB_QUEUE
              value: {{ .Values.extraEnv.JOB_QUEUE | quote }}
            - name: JOB_DEFINITION
              value: {{ .Values.extraEnv.JOB_DEFINITION | quote }}
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 10
