# ============================================================
# Author: TGibson
# File: services/scoring/helm/templates/service.yaml
# Repo: AWS EKS CI/CD (Commercial + GovCloud) via CloudFormation
# Version: 1.1
# Date: 2025-08-27
# ============================================================
apiVersion: v1
kind: Service
metadata:
  name: scoring
spec:
  type: {{ .Values.service.type }}
  selector: { app: scoring }
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
