# ============================================================
# Author: TGibson
# File: ops/k8s/externalsecrets-app.yaml
# Repo: AWS EKS CI/CD (Commercial + GovCloud) via CloudFormation
# Version: 1.1
# Date: 2025-08-27
# ============================================================
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: scoring-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: scoring-env
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /zt/prod/db/password
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: /zt/prod/smtp/password
