# ============================================================
# Author: TGibson
# File: ops/k8s/tenant-resourcequota.yaml
# Repo: AWS EKS CI/CD (Commercial + GovCloud) via CloudFormation
# Version: 1.0
# Date: 2025-08-27
# ============================================================

apiVersion: v1
kind: ResourceQuota
metadata:
  name: standard-tenant-quota
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "50"
