# ============================================================
# Author: TGibson
# File: templates/backup-vault-plan.yaml
# Repo: AWS EKS CI/CD (Commercial + GovCloud) via CloudFormation
# Version: 1.1
# Date: 2025-08-27
# ============================================================
AWSTemplateFormatVersion: '2010-09-09'
Description: Production Backup Vault + Plan with tag-based selections (Created 2025-08-28)
Parameters:
  BackupVaultName:
    Type: String
    Default: prod-backup-vault
  BackupKmsKeyArn:
    Type: String
    Default: ''
    Description: Optional KMS key ARN for vault encryption (leave blank to use AWS managed key)
  TagKey:
    Type: String
    Default: Backup
  TagValue:
    Type: String
    Default: Yes
  DailyRetentionDays:
    Type: Number
    Default: 35
  MonthlyRetentionMonths:
    Type: Number
    Default: 12
Resources:
  BackupVault:
    Type: AWS::Backup::BackupVault
    Properties:
      BackupVaultName: !Ref BackupVaultName
      EncryptionKeyArn: !If [ HasKms, !Ref BackupKmsKeyArn, !Ref AWS::NoValue ]
  BackupPlan:
    Type: AWS::Backup::BackupPlan
    Properties:
      BackupPlan:
        BackupPlanName: prod-backup-plan
        Rules:
          - RuleName: Daily-Backups
            TargetBackupVault: !Ref BackupVault
            ScheduleExpression: cron(0 8 * * ? *)
            StartWindowMinutes: 60
            CompletionWindowMinutes: 480
            Lifecycle:
              DeleteAfterDays: !Ref DailyRetentionDays
          - RuleName: Monthly-Backups
            TargetBackupVault: !Ref BackupVault
            ScheduleExpression: cron(0 9 1 * ? *)
            StartWindowMinutes: 60
            CompletionWindowMinutes: 1440
            Lifecycle:
              DeleteAfterDays: 365
  SelectionByTag:
    Type: AWS::Backup::BackupSelection
    Properties:
      BackupPlanId: !Ref BackupPlan
      BackupSelection:
        SelectionName: TagBasedSelection
        IamRoleArn: !GetAtt BackupRole.Arn
        ListOfTags:
          - ConditionType: STRINGEQUALS
            ConditionKey: !Ref TagKey
            ConditionValue: !Ref TagValue
  BackupRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: backup.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup
        - arn:aws:iam::aws:policy/AWSBackupServiceRolePolicyForRestores
Conditions:
  HasKms: !Not [ !Equals [ !Ref BackupKmsKeyArn, "" ] ]
Outputs:
  BackupVaultName:
    Value: !Ref BackupVault
  BackupPlanId:
    Value: !Ref BackupPlan
