AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role for Karpenter Controller (IRSA)
Parameters:
  ClusterName:
    Type: String
  OIDCProviderArn:
    Type: String
Resources:
  KarpenterControllerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref OIDCProviderArn
            Action: sts:AssumeRoleWithWebIdentity
      Policies:
        - PolicyName: karpenter-controller
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateLaunchTemplate
                  - ec2:CreateFleet
                  - ec2:RunInstances
                  - ec2:TerminateInstances
                  - ec2:CreateTags
                  - ec2:DeleteLaunchTemplate
                  - ec2:Describe*
                Resource: "*"
              - Effect: Allow
                Action: iam:PassRole
                Resource: "*"
              - Effect: Allow
                Action: pricing:GetProducts
                Resource: "*"
Outputs:
  KarpenterControllerRoleArn:
    Value: !GetAtt KarpenterControllerRole.Arn
