# ============================================================
# Author: TGibson
# File: templates/workload-deploy-iam.yaml
# Repo: AWS EKS CI/CD (Commercial + GovCloud) via CloudFormation
# Version: 1.1
# Date: 2025-08-27
# ============================================================

AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy role for a specific env in a workload account (map into aws-auth)

Parameters:
  ToolsAccountId: { Type: String }
  EnvName:       { Type: String, AllowedValues: [dev, stg, prod] }
  DeployRoleName:{ Type: String, Default: codebuild-deploy-env }

Resources:
  DeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref DeployRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { AWS: !Sub arn:${AWS::Partition}:iam::${ToolsAccountId}:role/${AppName}-codebuild-deploy-role }
            Action: sts:AssumeRole
      Policies:
        - PolicyName: eks-deploy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: [ 'eks:DescribeCluster' ]
                Resource: '*'
              - Effect: Allow
                Action: [ 'ecr:GetAuthorizationToken' ]
                Resource: '*'
              - Effect: Allow
                Action: [ 'logs:CreateLogGroup','logs:CreateLogStream','logs:PutLogEvents' ]
                Resource: '*'
