# ============================================================
# Author: TGibson
# File: ops/helm/templates/service.yaml
# Repo: AWS EKS CI/CD (Commercial + GovCloud) via CloudFormation
# Version: 1.0
# Date: 2025-08-27
# ============================================================

apiVersion: v1
kind: Service
metadata:
  name: {{ include "myservice.fullname" . }}
  labels: {{- include "myservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector: {{- include "myservice.selectorLabels" . | nindent 4 }}
