# ============================================================
# Author: TGibson
# File: ops/pipeline/buildspec-ecs-build.yml
# Repo: AWS EKS CI/CD (Commercial + GovCloud) via CloudFormation
# Version: 1.1
# Date: 2025-08-27
# ============================================================
version: 0.2
phases:
  pre_build:
    commands:
      - aws --version
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker build -t $IMAGE_URI -f app/Dockerfile .
      - docker push $IMAGE_URI
      - echo $IMAGE_URI > image_uri.txt
artifacts:
  files:
    - image_uri.txt
